#!/bin/bash
### ---
### name: 'MULTIQC_PRETRIM (MultiQC report - pretrim)'
### outputs:
### - 'pretrim_multiqc_report.html'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf -- $exit_status > /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/4e/676efd5a56a148ae9463f275599bf7/.exitcode
    set +u
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/4e/676efd5a56a148ae9463f275599bf7/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f PLN_2_fastqc.html
    rm -f SB_1_fastqc.html
    rm -f DM_1_fastqc.zip
    rm -f KT_2_fastqc.zip
    rm -f KT_2_fastqc.html
    rm -f SB_1_fastqc.zip
    rm -f DM_1_fastqc.html
    rm -f KT_1_fastqc.html
    rm -f PLN_1_fastqc.zip
    rm -f KT_1_fastqc.zip
    rm -f DM_2_fastqc.zip
    rm -f SB_2_fastqc.zip
    rm -f DM_2_fastqc.html
    rm -f PLN_1_fastqc.html
    rm -f SB_2_fastqc.html
    rm -f PLN_2_fastqc.zip
    ln -s /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/be/dae46d2b292f5edfc7277985f4ddd0/PLN_2_fastqc.html PLN_2_fastqc.html
    ln -s /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/2c/7775c12f554dbbd9455d18c1329e49/SB_1_fastqc.html SB_1_fastqc.html
    ln -s /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/e8/f3e520180734a262cbb28bca759143/DM_1_fastqc.zip DM_1_fastqc.zip
    ln -s /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/a5/445c96c964cc3179755ac5f2c01fff/KT_2_fastqc.zip KT_2_fastqc.zip
    ln -s /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/a5/445c96c964cc3179755ac5f2c01fff/KT_2_fastqc.html KT_2_fastqc.html
    ln -s /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/2c/7775c12f554dbbd9455d18c1329e49/SB_1_fastqc.zip SB_1_fastqc.zip
    ln -s /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/e8/f3e520180734a262cbb28bca759143/DM_1_fastqc.html DM_1_fastqc.html
    ln -s /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/a5/445c96c964cc3179755ac5f2c01fff/KT_1_fastqc.html KT_1_fastqc.html
    ln -s /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/be/dae46d2b292f5edfc7277985f4ddd0/PLN_1_fastqc.zip PLN_1_fastqc.zip
    ln -s /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/a5/445c96c964cc3179755ac5f2c01fff/KT_1_fastqc.zip KT_1_fastqc.zip
    ln -s /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/e8/f3e520180734a262cbb28bca759143/DM_2_fastqc.zip DM_2_fastqc.zip
    ln -s /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/2c/7775c12f554dbbd9455d18c1329e49/SB_2_fastqc.zip SB_2_fastqc.zip
    ln -s /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/e8/f3e520180734a262cbb28bca759143/DM_2_fastqc.html DM_2_fastqc.html
    ln -s /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/be/dae46d2b292f5edfc7277985f4ddd0/PLN_1_fastqc.html PLN_1_fastqc.html
    ln -s /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/2c/7775c12f554dbbd9455d18c1329e49/SB_2_fastqc.html SB_2_fastqc.html
    ln -s /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/be/dae46d2b292f5edfc7277985f4ddd0/PLN_2_fastqc.zip PLN_2_fastqc.zip
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /mnt/GDrive_01/Monash/21_Scripts/nf-mucimmuno/scRNAseq/work/4e/676efd5a56a148ae9463f275599bf7/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
